feat : completed_cnt, level 시스템 구현
LikeLion-at-DGU/backback_backend pull request #64
Opened 2023-08-11 07:04 UTC by minwoo0419

close #61 

매 월 마다 초기화는 아직 X

2023-08-11 07:39 UTC, minwoo0419 commented
매 월 초기화 구현 완료

2023-08-11 13:53 UTC, tkdwns414 requested changes
조금 수정 필요!

2023-08-11 13:53 UTC, tkdwns414 commented on community/models.py
> +
1. 파이썬은 snacke_case 사용하는 언어인데 함수 이름이 이상해요
2. profile app의 receivers.py랑 app.py 참고해서 receivers 이동시켜주세요

2023-08-11 13:53 UTC, tkdwns414 commented on community/models.py
> +            instance.writer.profile.save()
지우는거는 생성일자가 오늘인지 확인할 필요가 없고 '지워지는 인스턴스'의 생성 일자가 언제인지가 중요한 것 같은데 로직이 약간 이상해보입니다.

2023-08-13 19:08 UTC, tkdwns414 commented on community/models.py
> +            instance.writer.profile.save()
대충 이번달 안에거 지웠고 그날 그거 지워지면 작성된 오운완이 더이상 없다면 -1을 해주는 코드로 수정해주세요

2023-08-14 05:45 UTC, tkdwns414 approved these changes
LGTM

2023-08-14 05:45 UTC, merged